export const MOVE_FINISH = 'MOVE_FINISH'
export const MOVE_LEFT = 'MOVE_LEFT'
export const MOVE_RIGHT = 'MOVE_RIGHT'
export const MOVE_DOWN = 'MOVE_DOWN'
export const MOVE_CW = 'MOVE_CW'
export const MOVE_CCW = 'MOVE_CCW'
